### ISSUE TITLE
How to load BEIR/SBERT dataset into lightning dataloader? Could anyone please post snippet examples on the same?

### ISSUE THREAD

**Issue by techthiyanes** [webis-de/lightning-ir#29]

**Comment by fschlatt** [comment]
### BEIR

The BEIR datasets are available via https://ir-datasets.com/.

Depending on whether you want to access the documents, queries, or query-document pairs you need to use different datasets. Documents and queries are directly available. For query-document pairs, you need to feed a TREC-style run file into the dataset. Here is an example snippet for all three datasets.

```py
from lightning_ir import DocDataset, QueryDataset, RunDataset

doc_dataset = DocDataset("beir/arguana")
print(next(iter(doc_dataset)))

query_dataset = QueryDataset("beir/arguana")
print(next(iter(query_dataset)))

run_dataset = RunDataset("{PATH_TO_RUN_FILE}")
print(next(iter(run_dataset)))
```

### SBERT

The SBERT training triples are currently not supported within lightning-ir. We have support for the [ColBERT](https://huggingface.co/colbert-ir/colbertv2.0_msmarco_64way) training triples, [cross-architecture knowledge distillation](https://zenodo.org/record/4068216) triples, and [Rank-DistiLLM](https://zenodo.org/records/15131907) training datasets. All externally supported datasets can be found here https://github.com/webis-de/lightning-ir/tree/main/lightning_ir/data/external_datasets .

These above-mentioned datasets are available via the following snippet: 

```py
from lightning_ir import RunDataset, TupleDataset

# rank distillm datasets

# top 100 passages for 500k queries retrieved by colbertv2
colbert_dataset = RunDataset("msmarco-passage/train/rank-distillm-colbert")
print(next(iter(colbert_dataset)))
# top 100 passages for 500k queries retrieved by colbertv2 and re-ranked by set-encoder
set_encoder_dataset = RunDataset("msmarco-passage/train/rank-distillm-set-encoder")
print(next(iter(set_encoder_dataset)))
# top 100 passages for 10k queries retrieved by colbertv2 and re-ranked by rankzephyr
rankzephyr_dataset = RunDataset("msmarco-passage/train/rank-distillm-rankzephyr")
print(next(iter(rankzephyr_dataset)))

# colbert triples

colbert_dataset = TupleDataset("msmarco-passage/train/colbert-docpairs")
print(next(iter(colbert_dataset)))

# kd triples

kd_dataset = TupleDataset("msmarco-passage/train/kd-docpairs")
print(next(iter(kd_dataset)))
```

Integration of the SBERT triples shouldn't be too difficult. The following snippet registers the dataset with lightning-ir. The data must still be correctly parsed, though.

```py
import codecs
import json

from lightning_ir.data.external_datasets.ir_datasets_utils import ScoredDocTuples, register_new_dataset


class SBERTScordDocTuples(ScoredDocTuples):

    def docpairs_iter(self):
        with self._docpairs_dlc.stream() as f:
            f = codecs.getreader("utf8")(f)
            for line in f:
                data = json.loads(line)
                # TODO parse data and yield the docpairs


def register_sbert_docpairs():
    dlc_contents = {
        "url": "https://sbert.net/datasets/msmarco-hard-negatives.jsonl.gz",
        "expected_md5": "ecf8cafb10197fd7adf4f68aabd15d84",
        "cache_path": "msmarco-passage/train/sbert-docpairs.jsonl.gz",
    }
    register_new_dataset(
        "msmarco-passage/train/sbert-docpairs",
        docs="msmarco-passage",
        queries="msmarco-passage/train",
        qrels="msmarco-passage/train",
        docpairs=dlc_contents,
        DocpairsType=SBERTScordDocTuples,
    )

register_sbert_docpairs()

sbert_dataset = SBERTScordDocTuples("msmarco-passage/train/sbert-docpairs")
print(next(iter(sbert_dataset)))```

**Comment by techthiyanes** [comment]
Thanks for your reply. The above examples depict about how to load IR datasets. How could we load the dataset into its dataset object if i have my own queries,corpus and qrels jsonl files?

**Comment by fschlatt** [comment]
Integrating a custom dataset is supported via the `RegisterLocalDatasetCallback`. The [documentation](https://lightning-ir.webis.de/howto/dataset.html#registering-a-local-dataset) contains details on how to use it. If you have any questions, let me know and I will improve the documentation with your feedback

**Comment by techthiyanes** [comment]
Thank you @fschlatt . As per the above documentation, I have passed my corpus,queries jsonl files and qrels.tsv. After completing the registration of dataset, I am getting below error message while calling the object from tupledataset during train_dataset.docs

Unable to find dataset my-new-dataset in ir-datasets

**Comment by fschlatt** [comment]
Could you share a minimal snippet to reproduce your error? It sounds like the dataset is not properly registered, but it is difficult to judge why or where

**Comment by techthiyanes** [comment]
from lightning_ir import RegisterLocalDatasetCallback

register_dataset = RegisterLocalDatasetCallback(
    dataset_id='my-new-dataset',
    docs=r"fiqa\corpus.jsonl",
    queries=r"fiqa\queries.jsonl",
    qrels=r"fiqa\qrels\test.tsv",
)
from lightning_ir import TupleDataset, LightningIRTrainer, BiEncoderModule,DocDataset
train_dataset = TupleDataset("my-new-dataset")
train_dataset.docs

**Comment by fschlatt** [comment]
If you want to load a custom dataset programmatically, you can use the `register_new_dataset` function (the callback uses this function internally). Here is a code snippet to register the testing datasets located in this repository under `tests/data/corpus` and a corresponding run file located in `tests/data/runs`. Note, to use a `TupleDataset`, the newly registered dataset must have docpairs (the name for triples in ir-datasets) registered.

```py
from lightning_ir import DocDataset, QueryDataset, RunDataset, TupleDataset
from lightning_ir.data.external_datasets.ir_datasets_utils import register_new_dataset

register_new_dataset(
    "lightning-ir",
    docs="./tests/data/corpus/docs.tsv",
    queries="./tests/data/corpus/queries.tsv",
    qrels="./tests/data/corpus/qrels.tsv",
    docpairs="./tests/data/corpus/docpairs.tsv",
)

doc_dataset = DocDataset("lightning-ir")
print(next(iter(doc_dataset)))
query_dataset = QueryDataset("lightning-ir")
print(next(iter(query_dataset)))
tuple_dataset = TupleDataset("lightning-ir")
print(next(iter(tuple_dataset)))

run_dataset = RunDataset("./tests/data/runs/lightning-ir.tsv")
print(next(iter(run_dataset)))
```

**Comment by techthiyanes** [comment]
Thanks a lot @fschlatt .. Corpus dataset has been loaded now. But qrels.tsv is not loading where myqrels tsv file contains query-id,	corpus-id and score alone. I don't have docpairs at all. Could you please share sample format of all these here?

**Comment by fschlatt** [comment]
That's great to hear 👍 

Perhaps you could give me a few more details on what you are trying to achieve. Do you want to retrieve passages for queries using an already fine-tuned model? Do you already have a ranking and want to re-rank this ranking using an already fine-tuned model? Do you want to fine-tune your own model using fiqa data?

**Comment by techthiyanes** [comment]
I wanted to fine-tune my own model for fiqa dataset. After the completion of fine-tuning, I wanted to use this model to retrieve the relavant passages against my query. If you post the example format of the dataset, it would be really helpful to prepare similar format & go ahead with fine-tuning, indexing & retrieval.

**Comment by fschlatt** [comment]
Got it. For fine-tuning you require triples of the form `query_id\tdoc_id_1\tdoc_id_2` where `doc_id_1` is relevant to the query `query_id` and `doc_id_2` is not relevant (other formats are possible, but this is the most simple one). An example file can be found here: https://github.com/webis-de/lightning-ir/blob/main/tests/data/corpus/docpairs.tsv

**Comment by techthiyanes** [comment]
How about data format for qrels. my dataset has below format: 
query_id    	iteration	doc_id	score
genQ1	0	460230	1.0
genQ2	0	460230	1.0
genQ3	0	460230	1.0
genQ4	0	257122	1.0
genQ5	0	257122	1.0
genQ6	0	257122	1.0

It is failing due to which invalid literal for int() with base 10: 'score'

**Comment by techthiyanes** [comment]
I have loaded the dataset successfully. But now I'm unable to load the biencoder/cross encoder modules. 
from lightning_ir import BiEncoderModule, CrossEncoderModule

bi_encoder = BiEncoderModule("webis/bert-bi-encoder") ------Error: KeyError: 'bi-encoder'

For custom bi encoder module  :  Error TypeError: Can't instantiate abstract class CustomBiEncoderBertModel without an implementation for abstract method 'score'

**Comment by fschlatt** [comment]
Ah yes, I updated some things yesterday and forgot to update the model files on huggingface. One second.

**Comment by fschlatt** [comment]
Should now work https://huggingface.co/webis/bert-bi-encoder/commit/b5bd29d382b905f13d37946a2b5658647246c49b

**Comment by techthiyanes** [comment]
> Should now work https://huggingface.co/webis/bert-bi-encoder/commit/b5bd29d382b905f13d37946a2b5658647246c49b

This fix is for biencodermodule.. Custom bi encoder module is still not working. Still getting same error: Error TypeError: Can't instantiate abstract class CustomBiEncoderBertModel without an implementation for abstract method 'score'

**Comment by fschlatt** [comment]
A custom bi-encoder model is only necessary if you want to build a completely new type of model. If you want to fine-tune an SBERT/DPR type model, you can use the `DprModel` https://lightning-ir.webis.de/_autosummary/lightning_ir.models.dpr.html#module-lightning_ir.models.dpr

**Comment by techthiyanes** [comment]
> A custom bi-encoder model is only necessary if you want to build a completely new type of model. If you want to fine-tune an SBERT/DPR type model, you can use the `DprModel` https://lightning-ir.webis.de/_autosummary/lightning_ir.models.dpr.html#module-lightning_ir.models.dpr

Thanks a lot @fschlatt ..  Few recommendations here to post the below details into the documents. 1)Most of us will be consuming the SBERT models to fine-tune 2)Please post an example how to consume the custom datasets either from JSONL/TSV files along with column names for each file. 3)Using fine-tuned model, how to index, how to do search..

**Comment by fschlatt** [comment]
Thanks for the feedback @techthiyanes ! I will update the documentation 👍
